# Generated by Django 5.1.3 on 2025-03-14 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            (
                                "Faculty of Arts, Humanities and Social Sciences",
                                "Faculty of Arts, Humanities and Social Sciences",
                            ),
                            (
                                "Faculty of Education and Health Sciences",
                                "Faculty of Education and Health Sciences",
                            ),
                            ("Kemmy Business School", "Kemmy Business School"),
                            (
                                "Faculty of Science and Engineering",
                                "Faculty of Science and Engineering",
                            ),
                            (
                                "Irish World Academy of Music and Dance",
                                "Irish World Academy of Music and Dance",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            (
                                "Faculty of Arts, Humanities and Social Sciences",
                                "Faculty of Arts, Humanities and Social Sciences",
                            ),
                            (
                                "Faculty of Education and Health Sciences",
                                "Faculty of Education and Health Sciences",
                            ),
                            ("Kemmy Business School", "Kemmy Business School"),
                            (
                                "Faculty of Science and Engineering",
                                "Faculty of Science and Engineering",
                            ),
                            (
                                "Irish World Academy of Music and Dance",
                                "Irish World Academy of Music and Dance",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
