# Generated by Django 5.1.3 on 2025-03-15 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_alter_reviewer_user_alter_supervisor_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanParticipants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vulnerable_persons", models.BooleanField(default=True)),
                ("under_18", models.BooleanField(default=False)),
                ("patients", models.BooleanField(default=False)),
                ("staff", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubjectMatter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensitive_issues", models.BooleanField(default=True)),
                ("illegal_activities", models.BooleanField(default=False)),
                ("self_respect_risk", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EthicsForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clarifications", models.TextField()),
                ("application_title", models.CharField(max_length=255)),
                ("application_number", models.CharField(max_length=255)),
                ("supervisor_name", models.CharField(max_length=255)),
                ("supervisor_email", models.EmailField(max_length=254)),
                ("applicant_name", models.CharField(max_length=255)),
                ("applicant_email", models.EmailField(max_length=254)),
                ("project_title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("declaration_date", models.DateField()),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Under Review", "Under Review"),
                            ("Approved", "Approved"),
                            ("Major Clarifications", "Major Clarifications"),
                            ("Minor Clarifications", "Minor Clarifications"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.supervisor",
                    ),
                ),
                (
                    "human_participants",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ethics.humanparticipants",
                    ),
                ),
                (
                    "subject_matter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ethics.subjectmatter",
                    ),
                ),
            ],
        ),
    ]
