# Generated by Django 5.1.3 on 2025-03-15 11:12

import django.db.models.deletion
import ethics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ethicsform",
            name="human_participants",
            field=models.ForeignKey(
                default=ethics.models.HumanParticipants.get_default,
                on_delete=django.db.models.deletion.CASCADE,
                to="ethics.humanparticipants",
            ),
        ),
        migrations.AlterField(
            model_name="ethicsform",
            name="subject_matter",
            field=models.ForeignKey(
                default=ethics.models.SubjectMatter.get_default,
                on_delete=django.db.models.deletion.CASCADE,
                to="ethics.subjectmatter",
            ),
        ),
        migrations.AlterField(
            model_name="humanparticipants",
            name="staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="humanparticipants",
            name="vulnerable_persons",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subjectmatter",
            name="self_respect_risk",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subjectmatter",
            name="sensitive_issues",
            field=models.BooleanField(default=False),
        ),
    ]
